student_count = 11
puts "The student of Villains Academy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Wich of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# finally , we print the total number of students
print "Overall, we have #{student_count} great students"
